using System.Collections.Frozen;
using System.Collections.Generic;
using A = Aeon.Emulator.Keys;
using M = Microsoft.Xna.Framework.Input.Keys;

namespace AeonMonoGame;

internal static class KeyConverter
{
    extension(M input)
    {
        public bool TryConvert(out A aeonKeys) => lookup.TryGetValue(input, out aeonKeys);
    }

    private static readonly FrozenDictionary<M, A> lookup = new Dictionary<M, A>
    {
        [M.Escape] = A.Esc,
        [M.D1] = A.One,
        [M.D2] = A.Two,
        [M.D3] = A.Three,
        [M.D4] = A.Four,
        [M.D5] = A.Five,
        [M.D6] = A.Six,
        [M.D7] = A.Seven,
        [M.D8] = A.Eight,
        [M.D9] = A.Nine,
        [M.D0] = A.Zero,
        [M.OemMinus] = A.Minus,
        [M.OemPlus] = A.Equals,
        [M.Back] = A.Backspace,
        [M.Tab] = A.Tab,
        [M.Q] = A.Q,
        [M.W] = A.W,
        [M.E] = A.E,
        [M.R] = A.R,
        [M.T] = A.T,
        [M.Y] = A.Y,
        [M.U] = A.U,
        [M.I] = A.I,
        [M.O] = A.O,
        [M.P] = A.P,
        [M.OemOpenBrackets] = A.OpenBracket,
        [M.OemCloseBrackets] = A.CloseBracket,
        [M.Enter] = A.Enter,
        [M.LeftControl] = A.Ctrl,
        [M.A] = A.A,
        [M.S] = A.S,
        [M.D] = A.D,
        [M.F] = A.F,
        [M.G] = A.G,
        [M.H] = A.H,
        [M.J] = A.J,
        [M.K] = A.K,
        [M.L] = A.L,
        [M.OemSemicolon] = A.Semicolon,
        [M.OemQuotes] = A.Apostrophe,
        [M.OemTilde] = A.GraveApostrophe,
        [M.LeftShift] = A.LeftShift,
        [M.OemBackslash] = A.Backslash,
        [M.Z] = A.Z,
        [M.X] = A.X,
        [M.C] = A.C,
        [M.V] = A.V,
        [M.B] = A.B,
        [M.N] = A.N,
        [M.M] = A.M,
        [M.OemComma] = A.Comma,
        [M.OemPeriod] = A.Period,
        [M.OemQuestion] = A.Slash,
        [M.RightShift] = A.RightShift,
        [M.PrintScreen] = A.PrintScreen,
        [M.LeftAlt] = A.Alt,
        [M.Space] = A.Space,
        [M.CapsLock] = A.CapsLock,
        [M.F1] = A.F1,
        [M.F2] = A.F2,
        [M.F3] = A.F3,
        [M.F4] = A.F4,
        [M.F5] = A.F5,
        [M.F6] = A.F6,
        [M.F7] = A.F7,
        [M.F8] = A.F8,
        [M.F9] = A.F9,
        [M.F10] = A.F10,
        [M.NumLock] = A.NumLock,
        [M.Scroll] = A.ScrollLock,
        [M.NumPad7] = A.KeypadSeven,
        [M.NumPad8] = A.KeypadEight,
        [M.NumPad9] = A.KeypadNine,
        [M.Subtract] = A.KeypadMinus,
        [M.NumPad4] = A.KeypadFour,
        [M.NumPad5] = A.KeypadFive,
        [M.NumPad6] = A.KeypadSix,
        [M.Add] = A.KeypadPlus,
        [M.NumPad1] = A.KeypadOne,
        [M.NumPad2] = A.KeypadTwo,
        [M.NumPad3] = A.KeypadThree,
        [M.NumPad0] = A.KeypadZero,
        [M.Decimal] = A.KeypadPeriod,
        [M.Divide] = A.KeypadSlash,
        //[M.en KeypadEnter = 0x1CE0,
        [M.F11] = A.F11,
        [M.F12] = A.F12,
        [M.Insert] = A.Insert,
        [M.Delete] = A.Delete,
        [M.Home] = A.Home,
        [M.End] = A.End,
        [M.PageUp] = A.PageUp,
        [M.PageDown] = A.PageDown,
        [M.Left] = A.Left,
        [M.Right] = A.Right,
        [M.Up] = A.Up,
        [M.Down] = A.Down,
        [M.RightAlt] = A.RightAlt,
        [M.RightControl] = A.RightCtrl,
        [M.Pause] = A.Pause
    }.ToFrozenDictionary();
}
